[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  include_dir = ["cmd", "internal", "db"]
  delay = 500

[log]
  time = true
